/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RmigUs6JJxD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<Card
      className="w-full max-w-md bg-white dark:bg-gray-950 rounded-xl shadow-lg">
      <CardHeader className="px-6 pt-6">
        <CardTitle>Download YouTube Content</CardTitle>
        <CardDescription>Enter a YouTube link and choose your preferred format and quality.</CardDescription>
      </CardHeader>
      <CardContent className="px-6 py-4 space-y-4">
        <div className="space-y-2">
          <Label htmlFor="youtube-link">YouTube Link</Label>
          <Input
            id="youtube-link"
            placeholder="https://www.youtube.com/watch?v=dQw4w9WgXcQ" />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="format">Format</Label>
            <Select id="format">
              <SelectTrigger>
                <SelectValue placeholder="Select format" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="video">Video</SelectItem>
                <SelectItem value="audio">Audio</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="quality">Quality</Label>
            <Select id="quality">
              <SelectTrigger>
                <SelectValue placeholder="Select quality" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="720p">720p</SelectItem>
                <SelectItem value="1080p">1080p</SelectItem>
                <SelectItem value="1440p">1440p</SelectItem>
                <SelectItem value="2160p">2160p</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </CardContent>
      <CardFooter className="px-6 pb-6 flex justify-end">
        <Button>Download</Button>
      </CardFooter>
    </Card>)
  );
}
